### PR TITLE
Update Travis CI to R YAML

### PR DESCRIPTION
**Pull request by frenchja**
This PR updates the branch to follow the guidelines established in https://docs.travis-ci.com/user/languages/r/

# TODO
If desired, further Travis speed optimizations can be made by adding packages installed from source (as dependencies of the `r_github_packages`  to the `r_binary_packages` list, where they are instead added as APT packages.

### CODE REVIEW

**Comment by frenchja** [comment]
@abelcastilloavant @robertzk:

```r
> test_check("looker3")

1. Failure: extract_query_result returns a data frame --------------------------

`result` not equal to data.frame(ID = 1, VALUE = 2).

Attributes: < Length mismatch: comparison on first 2 components >
```

**Comment by frenchja** [comment]
I'm rusty, but are `lists` valid fake responses?

```r
httr::status_code(resp)
Error in UseMethod("status_code") : 
  no applicable method for 'status_code' applied to an object of class "list"
```

**Comment by frenchja** [comment]
@abelcastilloavant @robertzk, we have to do more than modify the class of the Tibble object:

https://github.com/frenchja/looker3/blob/master/tests/testthat/test-response_handlers.R#L64

```r
str(result)
'data.frame':	1 obs. of  2 variables:
 $ ID   : int 1
 $ VALUE: int 2
 - attr(*, "spec")=List of 2
  ..$ cols   :List of 2
  .. ..$ ID   : list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  .. ..$ VALUE: list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  ..$ default: list()
  .. ..- attr(*, "class")= chr  "collector_guess" "collector"
  ..- attr(*, "class")= chr "col_spec"

class(data.frame(ID=1, VALUE=2))
[1] "data.frame"
Browse[1]> str(data.frame(ID=1, VALUE=2))
'data.frame':	1 obs. of  2 variables:
 $ ID   : num 1
 $ VALUE: num 2
```

**Comment by robertzk** [comment]
Looking great @frenchja Thanks! I'll fix the failing test.

**Comment by frenchja** [comment]
@robertzk 

```r
attributes(result)$spec <- NULL
class(result) <- "data.frame"
expect_equal(result, data.frame(ID=as.integer(1), VALUE=as.integer(2)))
```

should fix it

**Pull request merged**
